services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: -p ${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
